### ISSUE TITLE
a post that my friend liked but missing filter

### ISSUE THREAD

**Issue by vpro16513428** [jurajivan/friendsfeed#2]
hello author , sorry my english not well at all
just want to report that might be something wrong with filter rule,i guess?
a post that my friend liked in the newsfeed but i didn't followed the post author!
i gladly give you the source html code about the post i just say above.
Maybe helpful for debug :)

**Comment by jurajivan** [comment]
The new version is coming soon, it may fix this problem. But please provide the HTML and I will check it. Thanks!

**Comment by vpro16513428** [comment]
_element_screenshot_

![element_screenshot](https://cloud.githubusercontent.com/assets/16053741/25739839/37f08ff4-31b6-11e7-8472-22d6b1d41600.png)

_element_htmlCode_txt_
[post_element.txt](https://github.com/jurajivan/friendsfeed/files/978589/post_element.txt)

**Comment by jurajivan** [comment]
This should be fixed in the 1.5+. Can you please check if such posts are filtered in your news feed?

**Comment by vpro16513428** [comment]
@jurajivan OK!I'll collect other stories that have same problem and put on here when I found it

**Comment by vpro16513428** [comment]
here have another story have same problem after update
**element_htmlCode_txt**
[post_element_2017_05_12.txt](https://github.com/jurajivan/friendsfeed/files/995444/post_element_2017_05_12.txt)

**Comment by jurajivan** [comment]
I've found the bug, it's fixed in the version 1.5.2. Again, thank you for your cooperation.

**Comment by vpro16513428** [comment]
I'm glad I can help :)
