### ISSUE TITLE
share failed!!

### ISSUE THREAD

**Issue by vpro16513428** [jurajivan/friendsfeed#3]
![screenshot-www facebook com-2017-05-12-09-14-58](https://cloud.githubusercontent.com/assets/16053741/25978312/0dd5bd46-36f4-11e7-9570-07ba75d16d9a.jpeg)
then I click share
![screenshot-www facebook com-2017-05-12-09-17-53](https://cloud.githubusercontent.com/assets/16053741/25978326/23d566aa-36f4-11e7-9822-7a74defa9019.jpeg)
then I click post
![screenshot-www facebook com-2017-05-12-09-18-10](https://cloud.githubusercontent.com/assets/16053741/25978332/35bbb3c4-36f4-11e7-80ad-c3278c3c2ab4.jpeg)
here comes error msg

**Comment by jurajivan** [comment]
@vpro16513428 Thanks for pointing out! I've pushed the new 1.5.1 version, it should be available from the Chrome Store in a few hours.
