### ISSUE TITLE
Remove the friends feed add

### ISSUE THREAD

**Issue by catskull** [jurajivan/friendsfeed#4]
![image](https://cloud.githubusercontent.com/assets/6233563/26233471/db7348c4-3c1a-11e7-9451-3b478cae3386.png)

What is the point of this? Please remove this add, or at the very least add a way to permanently disable it.

**Comment by jurajivan** [comment]
The point is to get more users. You can easily remove it with "Hide This" link.

![image](https://cloud.githubusercontent.com/assets/416587/26250932/f7653236-3cab-11e7-80ab-ef8ff87fd179.png)
